const users = [
  {
    id: 1,
    name: "Casper",
    isOnline: false,
    email: "casper@example.com",
    gender: "male",
    age: 28,
    city: "Gothenburg",
  },
  {
    id: 2,
    name: "Maja",
    isOnline: true,
    email: "maja@example.com",
    gender: "female",
    age: 36,
    city: "Malmo",
  },
  {
    id: 3,
    name: "Jonas",
    isOnline: false,
    email: "jonas@example.com",
    gender: "male",
    age: 29,
    city: "Malmo",
  },
  {
    id: 4,
    name: "Mikeal",
    isOnline: true,
    email: "mikeal@example.com",
    gender: "male",
    age: 44,
    city: "Stockholm",
  },
  {
    id: 5,
    name: "Lisa",
    isOnline: true,
    email: "lisa@example.com",
    gender: "female",
    age: 21,
    city: "Gothenburg",
  },
  {
    id: 6,
    name: "Carlos",
    isOnline: false,
    email: "carlos@example.com",
    gender: "male",
    age: 19,
    city: "Stockholm",
  },
];
